package effects;

public enum BuffType {
    HOLY,
    DE_HOLY,
    WEAKNESS,
    STUN,
    DISARM,
    CHANGE_ATTACK_POWER_OR_HEALTH_BUFF,
    CLEAR,
    FIRE_CELL,
    POISON,
    ANTI,
    ANTI_ALL_NEGATIVE,
    ANTI_ALL_POSITIVE,
    CHANGE_MANA,
    ADD_BUFF,
    SPECIAL_SITUATION_BUFF
}
